### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by SivaKumarOA** [Sath200/Employee#1]
1. Entities are not capitalised, unless the entity is an array of things"
https://github.com/Sath200/Employee/blob/master/src/main/kotlin/com/example/Employee/models/Holidays.kt#L8

2. Use data classes instead of normal class to represent POJOs
https://github.com/Sath200/Employee/blob/master/src/main/kotlin/com/example/Employee/models/Holidays.kt#L8

3. Use `val` instead of `var` by default:
https://github.com/Sath200/Employee/blob/master/src/main/kotlin/com/example/Employee/models/Employee.kt#L9 

4. Why query by two ids:
https://github.com/Sath200/Employee/blob/master/src/main/kotlin/com/example/Employee/repositories/BankAccountRepository.kt#L14

5. What do you need a `BankRequest` for:
https://github.com/Sath200/Employee/blob/master/src/main/kotlin/com/example/Employee/models/BankAccount.kt#L59

**Comment by Sath200** [comment]
1,2,3: Noted.
4. I actually used it to find a bank account by a particular bank account id. Now that I see it, I realised findById() would have been enough.
5. Since the bankAccount class had an employee object ,  in the json request body it was throwing an error saying missing value for JSON property employee. So, I created this bankAccountRequest with only those properties that we'll enter. 
Can I know other ways of doing it?

**Comment by SivaKumarOA** [comment]
Point 1, Correction: entity name in models are not pluralised, unless it represents a list.

**Comment by SivaKumarOA** [comment]
Point 2: Example for data classes:
https://github.com/shivsan/Surveyer/blob/master/src/main/kotlin/com/research/surveyor/models/Questionnaire.kt

**Comment by SivaKumarOA** [comment]
> 5. Since the bankAccount class had an employee object , in the json request body it was throwing an error saying missing value for JSON property employee. So, I created this bankAccountRequest with only those properties that we'll enter.
Can I know other ways of doing it?

If you're going to use an additional model, just for the API response, put it in the controller package, like this:
https://github.com/shivsan/Surveyer/blob/master/src/main/kotlin/com/research/surveyor/controllers/request/QuestionResponse.kt

Also, only classes that will be used in repository will have the `@Entity` annotion.

**Comment by SivaKumarOA** [comment]
When you make changes, create a separate branch in the name of the issue, like
`issue-1-fix-comments`,
then raise a PR from that branch to master. I will review the PR.
Do not push your newer changes directly to the master branch.

**Comment by Sath200** [comment]
> > 5. Since the bankAccount class had an employee object , in the json request body it was throwing an error saying missing value for JSON property employee. So, I created this bankAccountRequest with only those properties that we'll enter.
> >    Can I know other ways of doing it?
> 
> If you're going to use an additional model, just for the API response, put it in the controller package, like this: https://github.com/shivsan/Surveyer/blob/master/src/main/kotlin/com/research/surveyor/controllers/request/QuestionResponse.kt
> 
> Also, only classes that will be used in repository will have the `@Entity` annotion.

If I won't use @Entity, I cannot use @Id and @Generatedvalue to auto generate the id. 
Even if I directly use this @Generatedvalue in BankAccount model, it will throw an error in the following line saying no value passed for parameter id.
                    https://github.com/Sath200/Employee/blob/1ea25cc57126a8abedf2b78a47919d025b74f9dd/src/main/kotlin/com/example/Employee/services/BankAccountService.kt#L26

**Comment by Sath200** [comment]
> If I won't use @entity, I cannot use @id and @Generatedvalue to auto generate the id. Even if I directly use this @Generatedvalue in BankAccount model, it will throw an error in the following line saying no value passed for parameter id.
> 

Figured this out.
I created a branch and raised a PR.
